# Helm command: helm upgrade --install prometheus prometheus-community/kube-prometheus-stack -n monitoring --version 75.15.1 -f values_prometheus.hc.75.15.1.yml
global:
  imageRegistry: ""

crds:
  enabled: true
  upgrade: true

defaultRules:
  create: true
  rules:
    alertmanager: true
    etcd: false
    configReloaders: true
    general: true
    k8sContainerCpuUsageSecondsTotal: true
    k8sContainerMemoryCache: true
    k8sContainerMemoryRss: true
    k8sContainerMemorySwap: true
    k8sContainerResource: true
    k8sContainerMemoryWorkingSetBytes: true
    k8sPodOwner: true
    kubeApiserverAvailability: true
    kubeApiserverBurnrate: true
    kubeApiserverHistogram: true
    kubeApiserverSlos: true
    kubeControllerManager: false
    kubelet: true
    kubeProxy: false
    kubePrometheusGeneral: true
    kubePrometheusNodeRecording: true
    kubernetesApps: true
    kubernetesResources: true
    kubernetesStorage: true
    kubernetesSystem: true
    kubeSchedulerAlerting: false
    kubeSchedulerRecording: false
    kubeStateMetrics: true
    network: true
    node: true
    nodeExporterAlerting: true
    nodeExporterRecording: true
    prometheus: true
    prometheusOperator: true
    windows: false

alertmanager:
  enabled: true
  alertmanagerSpec:
    replicas: 1
    retention: 120h
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: managed
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 32Gi
    nodeSelector:
      agentpool: dremiocommon
    resources:
      requests:
        cpu: 100m
        memory: 100Mi

grafana:
  enabled: true
  replicas: 1
  adminPassword: admin123
  forceDeployDashboards: true
  defaultDashboardsEnabled: true
  defaultDashboardsTimezone: utc
  defaultDashboardsEditable: false
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
  persistence:
    annotations:
      "helm.sh/resource-policy": keep
    enabled: true
    storageClassName: managed
    accessModes: ["ReadWriteOnce"]
    size: 32Gi
  nodeSelector:
    agentpool: dremiocommon
  ingress:
    enabled: false
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
    - yourdomain.com
    path: /
    tls:
    - secretName: yourdomain.com
      hosts:
      - yourdomain.com


prometheus:
  enabled: true
  thanosService:
    enabled: false
  thanosServiceMonitor:
    enabled: false
  thanosServiceExternal:
    enabled: false
  prometheusSpec:
    nodeSelector:
      agentpool: dremiocommon
    retention: 30d
    retentionSize: "256GiB"
    replicas: 1
    scrapeInterval: "5s"
    scrapeTimeout: "5s"          # Added - must be less than or equal to scrapeInterval
    evaluationInterval: "5s"      # Added - how often to evaluate rules
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: managed-premium
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 256Gi
    resources:
      requests:
        cpu: 1000m
        memory: 1024Mi
    # Otherwise the pod monitor does not work. By default it is true
    podMonitorSelectorNilUsesHelmValues: false

prometheusOperator:
  enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
  # Required for use in managed kubernetes clusters (such as AWS EKS) with custom CNI (such as calico),
  # because control-plane managed by AWS cannot communicate with pods' IP CIDR and admission webhooks are not working
  hostNetwork: false
  nodeSelector:
    agentpool: dremiocommon

kubeStateMetrics:
  enabled: true

kube-state-metrics:
  nodeSelector:
    agentpool: dremiocommon

kubernetesServiceMonitors:
  enabled: true

kubeApiServer:
  enabled: true

kubelet:
  enabled: true

kubeControllerManager:
  enabled: false

coreDns:
  enabled: true

kubeDns:
  enabled: false

kubeEtcd:
  enabled: false

kubeScheduler:
  enabled: false

kubeProxy:
  enabled: false

nodeExporter:
  enabled: true
  operatingSystems:
    linux:
      enabled: true
    darwin:
      enabled: false

thanosRuler:
  enabled: false