{
 "title": "Dremio Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Dremio Namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\"},namespace)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Top Line Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Duration since Master Coordinator down",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{namespace=\"$namespace\", container=\"dremio-master-coordinator\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Coordinators",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{namespace=\"$namespace\", container=~\"dremio-master-coordinator|dremio-coordinator\"} == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Engine Details",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "count by (k8s_statefulset_name) (up{namespace=\"$namespace\", container=\"dremio-executor\"} == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime % - Master - Past 7 days",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(up{namespace=\"$namespace\", container=\"dremio-master-coordinator\"}[7d])) / sum(count_over_time(up{namespace=\"$namespace\", container=\"dremio-master-coordinator\"}[7d])) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime hours - Master - past 7 days",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(up{namespace=\"$namespace\", container=\"dremio-master-coordinator\"}[7d])) / sum(count_over_time(up{namespace=\"$namespace\", container=\"dremio-master-coordinator\"}[7d]))  *7 *24",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime %- Master - past 30 days",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(up{namespace=\"$namespace\", container=\"dremio-master-coordinator\"}[30d])) / sum(count_over_time(up{namespace=\"$namespace\", container=\"dremio-master-coordinator\"}[30d])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime hours - Master - past 30 days",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(up{namespace=\"$namespace\", container=\"dremio-master-coordinator\"}[30d])) / sum(count_over_time(up{namespace=\"$namespace\", container=\"dremio-master-coordinator\"}[30d]))  *30 *24",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# of queries in past 7 days",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(jobs_total{namespace=\"$namespace\", container=\"dremio-master-coordinator\"}[7d])) + sum(increase(jobs_failed_total{namespace=\"$namespace\", container=\"dremio-master-coordinator\"}[7d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query volume trend (vs yesterday)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(jobs_total{namespace=\"$namespace\", container=\"dremio-master-coordinator\"}[1d])) + sum(increase(jobs_failed_total{namespace=\"$namespace\", container=\"dremio-master-coordinator\"}[1d]))) - (sum(increase(jobs_total{namespace=\"$namespace\", container=\"dremio-master-coordinator\"}[1d] offset 1d)) + sum(increase(jobs_failed_total{namespace=\"$namespace\", container=\"dremio-master-coordinator\"}[1d] offset 1d)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jobs Failed % last 7 days",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(jobs_failed_total{namespace=\"$namespace\", container=\"dremio-master-coordinator\"}[7d])) /\r\n(sum(increase(jobs_total{namespace=\"$namespace\", container=\"dremio-master-coordinator\"}[7d])) + sum(increase(jobs_failed_total{namespace=\"$namespace\", container=\"dremio-master-coordinator\"}[7d]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jobs Failed % last hour",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(jobs_failed_total{namespace=\"$namespace\", container=\"dremio-master-coordinator\"}[1h])) /\r\n(sum(increase(jobs_total{namespace=\"$namespace\", container=\"dremio-master-coordinator\"}[1h])) + sum(increase(jobs_failed_total{namespace=\"$namespace\", container=\"dremio-master-coordinator\"}[1h]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# of queries in the past 30 days",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(jobs_total{namespace=\"$namespace\", container=\"dremio-master-coordinator\"}[30d])) + sum(increase(jobs_failed_total{namespace=\"$namespace\", container=\"dremio-master-coordinator\"}[30d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query volume trend (vs last week)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(jobs_total{namespace=\"$namespace\", container=\"dremio-master-coordinator\"}[7d])) + sum(increase(jobs_failed_total{namespace=\"$namespace\", container=\"dremio-master-coordinator\"}[7d]))) - (sum(increase(jobs_total{namespace=\"$namespace\", container=\"dremio-master-coordinator\"}[7d] offset 7d)) + sum(increase(jobs_failed_total{namespace=\"$namespace\", container=\"dremio-master-coordinator\"}[7d] offset 7d)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jobs Failed % last 30 days",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(jobs_failed_total{namespace=\"$namespace\", container=\"dremio-master-coordinator\"}[30d])) /\r\n(sum(increase(jobs_total{namespace=\"$namespace\", container=\"dremio-master-coordinator\"}[30d])) + sum(increase(jobs_failed_total{namespace=\"$namespace\", container=\"dremio-master-coordinator\"}[30d]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number Jobs Failed Last Hour",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(jobs_failed_total{namespace=\"$namespace\", container=\"dremio-master-coordinator\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% change Avg Running Time last hour compared to same hour 7 days ago",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  (\r\n    sum(increase(query_running_time_seconds_sum{namespace=\"$namespace\"}[1h]))\r\n    /\r\n    sum(increase(query_running_time_seconds_count{namespace=\"$namespace\"}[1h]))\r\n  )\r\n  -\r\n  (\r\n    sum(increase(query_running_time_seconds_sum{namespace=\"$namespace\"}[1h] offset 7d))\r\n    /\r\n    sum(increase(query_running_time_seconds_count{namespace=\"$namespace\"}[1h] offset 7d))\r\n  )\r\n)\r\n/\r\n(\r\n  sum(increase(query_running_time_seconds_sum{namespace=\"$namespace\"}[1h] offset 7d))\r\n  /\r\n  sum(increase(query_running_time_seconds_count{namespace=\"$namespace\"}[1h] offset 7d))\r\n)\r\n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% change Avg Running Time last hour compared same hour 24 hours ago",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  (\r\n    sum(increase(query_running_time_seconds_sum{namespace=\"$namespace\"}[1h]))\r\n    /\r\n    sum(increase(query_running_time_seconds_count{namespace=\"$namespace\"}[1h]))\r\n  )\r\n  -\r\n  (\r\n    sum(increase(query_running_time_seconds_sum{namespace=\"$namespace\"}[1h] offset 1d))\r\n    /\r\n    sum(increase(query_running_time_seconds_count{namespace=\"$namespace\"}[1h] offset 1d))\r\n  )\r\n)\r\n/\r\n(\r\n  sum(increase(query_running_time_seconds_sum{namespace=\"$namespace\"}[1h] offset 1d))\r\n  /\r\n  sum(increase(query_running_time_seconds_count{namespace=\"$namespace\"}[1h] offset 1d))\r\n)\r\n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Jobs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "max(irate(jobs_total{container=\"dremio-master-coordinator\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Num Jobs"
    },
    {
     "expr": "sum(irate(jobs_failed{container=\"dremio-master-coordinator\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Failed Jobs"
    }
   ]
  },
  {
   "title": "Active Reflections and Failed Reflections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "max by(pod) (reflections_active{pod=\"dremio-master-0\", namespace=\"$namespace\"})",
     "legendFormat": "Active Reflections"
    },
    {
     "expr": "sum by(pod) (reflections_failed{pod=\"dremio-master-0\", namespace=\"$namespace\"})",
     "legendFormat": "Failed Reflections"
    }
   ]
  },
  {
   "title": "Average Times Per Query Phase - Last Hour",
   "type": "canvas",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(query_pending_time_seconds_sum{namespace=\"$namespace\"}[1h])) / sum(increase(query_pending_time_seconds_count{namespace=\"$namespace\"}[1h]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(query_metadata_retrieval_time_seconds_sum{namespace=\"$namespace\"}[1h])) / sum(increase(query_metadata_retrieval_time_seconds_count{namespace=\"$namespace\"}[1h]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(query_planning_time_seconds_sum{namespace=\"$namespace\"}[1h])) / sum(increase(query_planning_time_seconds_count{namespace=\"$namespace\"}[1h]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(query_engine_start_time_seconds_sum{namespace=\"$namespace\"}[1h])) / sum(increase(query_engine_start_time_seconds_count{namespace=\"$namespace\"}[1h]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(query_queued_time_seconds_sum{namespace=\"$namespace\"}[1h])) / sum(increase(query_queued_time_seconds_count{namespace=\"$namespace\"}[1h]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(query_execution_planning_time_seconds_sum{namespace=\"$namespace\"}[1h])) / sum(increase(query_execution_planning_time_seconds_count{namespace=\"$namespace\"}[1h]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(query_starting_time_seconds_sum{namespace=\"$namespace\"}[1h])) / sum(increase(query_starting_time_seconds_count{namespace=\"$namespace\"}[1h]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(query_running_time_seconds_sum{namespace=\"$namespace\"}[1h])) / sum(increase(query_running_time_seconds_count{namespace=\"$namespace\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Dremio - Coordinator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Coordinator - Command Pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "max(jobs_command_pool_active_threads)",
     "legendFormat": "Active Threads"
    },
    {
     "expr": "max(jobs_command_pool_queue_size)",
     "legendFormat": "Queue Size"
    },
    {
     "expr": "max(jobs_command_pool_reacquire_queue_size)",
     "legendFormat": "Reaquire Pool Size"
    }
   ]
  },
  {
   "title": "Coordinator - Heap Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pod) (memory_heap_used{container=\"dremio-master-coordinator\", namespace=\"$namespace\", job=\"$namespace/dremio-pod-monitor\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "max by(namespace) (memory_heap_max{container=\"dremio-master-coordinator\", namespace=\"$namespace\", job=\"$namespace/dremio-pod-monitor\"})",
     "legendFormat": "Max Heap"
    }
   ]
  },
  {
   "title": "Coordinator - Direct Memory ",
   "type": "timeseries",
   "description": "This is the sum of JVM, Netty and Arrow direct memory",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pod) (dremio_memory_jvm_direct_current{namespace=\"$namespace\", container=\"dremio-master-coordinator\"})",
     "legendFormat": "JVM Direct Current: {{pod}}"
    },
    {
     "expr": "max by(pod) (dremio_memory_apache_arrow_direct_current{namespace=\"$namespace\",container=\"dremio-master-coordinator\"}) ",
     "legendFormat": "Arrow Memory: {{pod}}"
    },
    {
     "expr": "max by(pod) (dremio_memory_netty_direct_memory_current{namespace=\"$namespace\",container=\"dremio-master-coordinator\"})",
     "legendFormat": "Netty Direct: {{pod}}"
    }
   ]
  },
  {
   "title": "Coordinator - Buffer Pool Direct Capacity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pod) (buffer_pool_direct_capacity{container=\"dremio-master-coordinator\", namespace=\"$namespace\", job=\"$namespace/dremio-pod-monitor\"})",
     "legendFormat": "Capacity: {{pod}}"
    },
    {
     "expr": "max by(pod) (buffer_pool_direct_used{container=\"dremio-master-coordinator\", namespace=\"$namespace\", job=\"$namespace/dremio-pod-monitor\"})",
     "legendFormat": "Used: {{pod}}"
    }
   ]
  },
  {
   "title": "Coordinator - CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by(pod) (irate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"dremio-master-coordinator\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", container=\"dremio-master-coordinator\", resource=\"cpu\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", container=\"dremio-master-coordinator\", resource=\"cpu\"})",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "Coordinator - Memory Usage (Working Set Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pod) (container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\", container=\"dremio-master-coordinator\"})",
     "legendFormat": "RSS {{pod}}"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", container=\"dremio-master-coordinator\", resource=\"memory\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$namespace\", container=\"dremio-master-coordinator\", resource=\"memory\"})",
     "legendFormat": "limits"
    },
    {
     "expr": "max by(pod) (container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\", container=\"dremio-master-coordinator\"})",
     "legendFormat": "WSS {{pod}}"
    }
   ]
  },
  {
   "title": "Coordinator - Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "max by(pod) (irate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"dremio-master-.*\"}[$__rate_interval]))",
     "legendFormat": "Receive: {{pod}}"
    },
    {
     "expr": "max by(pod) (irate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"dremio-master-.*\"}[$__rate_interval]))",
     "legendFormat": "Transmit: {{pod}}"
    }
   ]
  },
  {
   "title": "Coordinator - Rate of Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by(pod) (irate(container_network_receive_packets_dropped_total{namespace=\"$namespace\", pod=~\"dremio-master-.*\"}[$__rate_interval]))",
     "legendFormat": "Receive: {{pod}}"
    },
    {
     "expr": "sum by(pod) (irate(container_network_transmit_packets_dropped_total{namespace=\"$namespace\", pod=~\"dremio-master-.*\"}[$__rate_interval]))",
     "legendFormat": "Transmit: {{pod}}"
    }
   ]
  },
  {
   "title": "Coordinator - IOPS (Reads+Writes)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ceil(sum by(pod) (rate(container_fs_reads_total{container=\"dremio-master-coordinator\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", namespace=\"$namespace\"}[$__rate_interval]) + rate(container_fs_writes_total{container=\"dremio-master-coordinator\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Coordinator - Throughput (Read+Write)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_fs_reads_bytes_total{container=\"dremio-master-coordinator\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", namespace=\"$namespace\"}[$__rate_interval]) + rate(container_fs_writes_bytes_total{container=\"dremio-master-coordinator\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Coordinator - JVM GC pause count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "sum by(pod) (irate(jvm_gc_pause_seconds_count{namespace=\"$namespace\", container=\"dremio-master-coordinator\"}[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Coordinator - JVM Max GC pause",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 76 },
   "targets": [
    {
     "expr": "max by(pod) (jvm_gc_pause_seconds_max{namespace=\"$namespace\", container=\"dremio-master-coordinator\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Dremio - Executors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Executor - Number Nodes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 84 },
   "targets": [
    {
     "expr": "kube_statefulset_replicas{namespace=\"$namespace\", statefulset=~\"dremio-executor.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executor - CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by(pod) (irate(process_cpu_seconds_total{namespace=\"$namespace\", container=\"dremio-executor\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", container=\"dremio-executor\", resource=\"cpu\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$namespace\", container=\"dremio-executor\", resource=\"cpu\"})",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "Executor - Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pod) (container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\", container=\"dremio-executor\"})",
     "legendFormat": "WSS {{pod}}"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", container=\"dremio-executor\", resource=\"memory\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$namespace\", container=\"dremio-executor\", resource=\"memory\"})",
     "legendFormat": "limits"
    },
    {
     "expr": "max by(pod) (container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\", container=\"dremio-executor\"})",
     "legendFormat": "RSS {{pod}}"
    }
   ]
  },
  {
   "title": "Executor - Heap Used",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pod) (memory_heap_used{container=\"dremio-executor\", namespace=\"$namespace\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "max(memory_heap_max{container=\"dremio-executor\", namespace=\"$namespace\"})",
     "legendFormat": "Max Heap"
    }
   ]
  },
  {
   "title": "Executor - Network Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "SUM by(pod) (irate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"dremio-executor-.*\"}[$__rate_interval]) + irate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"dremio-executor-.*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Executor - Rate of Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by(pod) (irate(container_network_transmit_packets_dropped_total{namespace=\"$namespace\", pod=~\"dremio-executor-.*\"}[$__rate_interval])\r\n+ irate(container_network_receive_packets_dropped_total{namespace=\"$namespace\", pod=~\"dremio-executor-.*\"}[$__rate_interval])\r\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Executor - IOPS (Reads+Writes)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ceil(sum by(pod) (rate(container_fs_reads_total{container=\"dremio-executor\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", namespace=\"$namespace\"}[$__rate_interval]) + rate(container_fs_writes_total{container=\"dremio-executor\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Executor - Throughput (Read+Write)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_fs_reads_bytes_total{container=\"dremio-executor\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", namespace=\"$namespace\"}[$__rate_interval]) + rate(container_fs_writes_bytes_total{container=\"dremio-executor\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Executor - Dremio Memory Direct",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pod) (dremio_memory_netty_direct_memory_current{container=\"dremio-executor\", namespace=\"$namespace\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "max(dremio_memory_netty_direct_memory_max{container=\"dremio-executor\", namespace=\"$namespace\"})",
     "legendFormat": "Max Direct"
    }
   ]
  },
  {
   "title": "Executor - Buffer Pool Direct",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pod) (buffer_pool_direct_used{container=\"dremio-executor\", namespace=\"$namespace\"})",
     "legendFormat": "USED: {{pod}}"
    },
    {
     "expr": "max by(pod) (buffer_pool_direct_capacity{container=\"dremio-executor\", namespace=\"$namespace\"})",
     "legendFormat": "CAP: {{pod}}"
    }
   ]
  },
  {
   "title": "Executor - JVM GC pause count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 121 },
   "targets": [
    {
     "expr": "sum by(pod) (irate(jvm_gc_pause_seconds_count{namespace=\"$namespace\", container=\"dremio-executor\"}[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Executor - JVM Max GC pause",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 121 },
   "targets": [
    {
     "expr": "max by(pod) (jvm_gc_pause_seconds_max{namespace=\"$namespace\", container=\"dremio-executor\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executor - Waiting Threads Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 128 },
   "targets": [
    {
     "expr": "max by(pod) (threads_waiting_count{namespace=\"$namespace\", container=\"dremio-executor\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Executor - Threads Active",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 128 },
   "targets": [
    {
     "expr": "max by(pod) (threads_count{namespace=\"$namespace\", container=\"dremio-executor\"} - threads_waiting_count{namespace=\"$namespace\", container=\"dremio-executor\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Executor - Sleep Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by(pod) (irate(exec_frag_sleep_time_sum{namespace=\"$namespace\", container=\"dremio-executor\"}[$__interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Executor - Active Fragments",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 135 },
   "targets": [
    {
     "expr": "max by(pod) (exec_fragments_active{namespace=\"$namespace\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Kubernetes - Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 142 } },
  {
   "title": "Host Node - Pod Mapping",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 143 },
   "targets": [
    {
     "expr": "label_join(\r\n sum by(node, host_ip, pod, pod_ip) (kube_pod_info{namespace=\"$namespace\", created_by_kind=\"StatefulSet\"}),\r\n \"instance\",\":9100\",\"host_ip\", \"doesmotexist\")"
    }
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(instance) (instance:node_cpu_utilisation:rate5m{job=\"node-exporter\"}) != 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Saturation (Load1 per CPU)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(instance) (instance:node_load1_per_cpu:ratio{job=\"node-exporter\"} != 0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(instance) (instance:node_memory_utilisation:ratio{job=\"node-exporter\"} != 0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Saturation (Major Page Faults)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "rds" } },
   "targets": [
    {
     "expr": "max by(instance) (instance:node_vmstat_pgmajfault:rate5m{job=\"node-exporter\"}) != 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Utilisation (Bytes Receive/Transmit)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 165 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "max by(instance) (instance:node_network_receive_bytes_excluding_lo:rate5m{job=\"node-exporter\"}) != 0",
     "legendFormat": "Receive {{instance}}"
    },
    {
     "expr": "sum by(instance) (instance:node_network_transmit_bytes_excluding_lo:rate5m{job=\"node-exporter\"} != 0)",
     "legendFormat": "Transmit {{instance}}"
    }
   ]
  },
  {
   "title": "Network Saturation (Drops Receive/Transmit)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 165 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "instance:node_network_receive_drop_excluding_lo:rate5m{job=\"node-exporter\"} != 0",
     "legendFormat": "Receive {{instance}}"
    },
    {
     "expr": "instance:node_network_transmit_drop_excluding_lo:rate5m{job=\"node-exporter\"} != 0",
     "legendFormat": "Transmit {{instance}}"
    }
   ]
  },
  {
   "title": "Disk IO Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(instance, device) (instance_device:node_disk_io_time_seconds:rate5m{job=\"node-exporter\"}) != 0",
     "legendFormat": "{{instance}} - {{device}}"
    }
   ]
  },
  {
   "title": "Disk IO Saturation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(instance, device) (instance_device:node_disk_io_time_weighted_seconds:rate5m{job=\"node-exporter\"}) != 0",
     "legendFormat": "{{instance}} - {{device}}"
    }
   ]
  },
  {
   "title": "IO Wait in %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 179 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(max by (instance) (irate(node_cpu_seconds_total{mode=\"iowait\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Space Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 179 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sort_desc(1 -\n  (\n   max without (mountpoint, fstype) (node_filesystem_avail_bytes{job=\"node-exporter\", fstype!=\"\"})\n   /\n   max without (mountpoint, fstype) (node_filesystem_size_bytes{job=\"node-exporter\", fstype!=\"\"})\n  ) != 0\n)\n",
     "legendFormat": "{{instance}} - {{device}}"
    }
   ]
  },
  { "title": "Kubernetes - Cluster Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 186 } },
  {
   "title": "Cluster CPU Utilisation",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 187 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(cluster:node_cpu:ratio_rate5m)"
    }
   ]
  },
  {
   "title": "Cluster Memory Utilisation",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 187 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - sum(:node_memory_MemAvailable_bytes:sum) / sum(node_memory_MemTotal_bytes{job=\"node-exporter\"})"
    }
   ]
  },
  {
   "title": "Cluster CPU Requests",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 187 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(namespace_cpu:kube_pod_container_resource_requests:sum{}) / sum(kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Cluster CPU Limits",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 187 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(namespace_cpu:kube_pod_container_resource_limits:sum{}) / sum(kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Cluster Memory Requests",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 187 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(namespace_memory:kube_pod_container_resource_requests:sum{}) / sum(kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Cluster Memory Limits",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 187 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(namespace_memory:kube_pod_container_resource_limits:sum{}) / sum(kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 192 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 192 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\", namespace=\"$namespace\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Receive Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 198 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 198 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}