---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: dremio-coordinator
provisioner: disk.csi.azure.com
parameters:
  skuname: Premium_LRS
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer