---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: dremio-coordinator
provisioner: disk.csi.azure.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  skuName: Premium_ZRS

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: dremio-logs
provisioner: disk.csi.azure.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  skuName: StandardSSD_ZRS

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: dremio-mongodb
provisioner: disk.csi.azure.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  skuName: Premium_ZRS

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: dremio-nats
provisioner: disk.csi.azure.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  skuName: StandardSSD_ZRS

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: dremio-opensearch
provisioner: disk.csi.azure.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  skuName: Premium_ZRS

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: dremio-zk
provisioner: disk.csi.azure.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  skuName: StandardSSD_ZRS