---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: dremiocommon
spec:
  template:
    metadata:
      labels:
        agentpool: dremiocommon
    spec:
      nodeClassRef:
        group: karpenter.azure.com
        kind: AKSNodeClass
        name: default
      requirements:
        - key: "karpenter.azure.com/sku-name"
          operator: In
          values: [ "Standard_D2ps_v5" ]
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: [ "eastus-1" ]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: [ "on-demand" ]
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s

---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: dremiocoord
spec:
  template:
    metadata:
      labels:
        agentpool: dremiocoord
    spec:
      nodeClassRef:
        group: karpenter.azure.com
        kind: AKSNodeClass
        name: default
      requirements:
        - key: "karpenter.azure.com/sku-name"
          operator: In
          values: [ "Standard_D16ps_v5" ]
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: [ "eastus-1" ]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: [ "on-demand" ]
  disruption:
    budgets:
      - nodes: 10%
    consolidateAfter: 30s
    consolidationPolicy: WhenEmptyOrUnderutilized

---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: dremioexec
spec:
  template:
    metadata:
      labels:
        agentpool: dremioexec
    spec:
      nodeClassRef:
        group: karpenter.azure.com
        kind: AKSNodeClass
        name: default
      requirements:
        - key: "karpenter.azure.com/sku-name"
          operator: In
          values: [ "Standard_E16pds_v5" ]
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: [ "eastus-1" ]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: [ "on-demand" ]
  disruption:
    budgets:
      - nodes: 10%
    consolidateAfter: 30s
    consolidationPolicy: WhenEmptyOrUnderutilized