---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: dremio-common
spec:
  template:
    metadata:
      labels:
        pool: dremio-common
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: default
#      taints:
#        - key: dremio
#          effect: NoExecute
      requirements:
        - key: "node.kubernetes.io/instance-type"
          operator: In
          values: [ "c8g.large" ]
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: [ "eu-central-1c" ]
        - key: "kubernetes.io/arch"
          operator: In
          values: [ "arm64" ]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: [ "on-demand" ]
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s

---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: dremio-coordinator
spec:
  template:
    metadata:
      labels:
        pool: dremio-coordinator
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: default
#      taints:
#        - key: dremio
#          effect: NoExecute
      requirements:
        - key: "node.kubernetes.io/instance-type"
          operator: In
          values: [ "m8g.4xlarge", "m8g.8xlarge" ]
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: [ "eu-central-1c" ]
        - key: "kubernetes.io/arch"
          operator: In
          values: [ "arm64" ]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: [ "on-demand" ]
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s

---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: dremio-executor
spec:
  template:
    metadata:
      labels:
        pool: dremio-executor
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: default
#      taints:
#        - key: dremio
#          effect: NoExecute
      requirements:
        - key: "node.kubernetes.io/instance-type"
          operator: In
          values: [ "r8gd.4xlarge", "m8gd.8xlarge" ]
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: [ "eu-central-1a", "eu-central-1b", "eu-central-1c"]
        - key: "kubernetes.io/arch"
          operator: In
          values: [ "arm64" ]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: [ "on-demand" ]
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s