---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: dremio-coordinator
provisioner: ebs.csi.eks.amazonaws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: io2
  iops: "6000"
  encrypted: "true"

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: dremio-logs
provisioner: ebs.csi.eks.amazonaws.com
volumeBindingMode: WaitForFirstConsumer
# gp3 baseline is 3000 IOPS
parameters:
  type: gp3
  encrypted: "true"

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: dremio-mongodb
provisioner: ebs.csi.eks.amazonaws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: io2
  iops: "6000"
  encrypted: "true"

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: dremio-nats
provisioner: ebs.csi.eks.amazonaws.com
volumeBindingMode: WaitForFirstConsumer
# gp3 baseline is 3000 IOPS
parameters:
  type: gp3
  encrypted: "true"

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: dremio-opensearch
provisioner: ebs.csi.eks.amazonaws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: io2
  iops: "6000"
  encrypted: "true"

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: dremio-zk
provisioner: ebs.csi.eks.amazonaws.com
volumeBindingMode: WaitForFirstConsumer
# gp3 baseline is 3000 IOPS
parameters:
  type: gp3
  encrypted: "true"

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: dremio-backup
provisioner: ebs.csi.eks.amazonaws.com
volumeBindingMode: WaitForFirstConsumer
# gp3 baseline is 3000 IOPS
parameters:
  type: gp3
  encrypted: "true"