---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: dremio-general
spec:
  template:
    metadata:
      labels:
        pool: dremio-general
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: default
#      taints:
#        - key: dremio
#          effect: NoExecute
      requirements:
        - key: "node.kubernetes.io/instance-type"
          operator: In
          values: [ "m6g.4xlarge" ]
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: [ "eu-central-1c" ]
        - key: "kubernetes.io/arch"
          operator: In
          values: [ "arm64" ]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: [ "on-demand" ]
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s
  limits:
    cpu: "48"

---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: dremio-coordinator
spec:
  template:
    metadata:
      labels:
        pool: dremio-coordinator
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: default
#      taints:
#        - key: dremio
#          effect: NoExecute
      requirements:
        - key: "node.kubernetes.io/instance-type"
          operator: In
          values: [ "r6g.4xlarge", "m6g.8xlarge" ]
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: [ "eu-central-1c" ]
        - key: "kubernetes.io/arch"
          operator: In
          values: [ "arm64" ]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: [ "on-demand" ]
  disruption:
    budgets:
      - nodes: 10%
    consolidateAfter: 30s
    consolidationPolicy: WhenEmptyOrUnderutilized

---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: dremio-executor
spec:
  template:
    metadata:
      labels:
        pool: dremio-executor
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: default
#      taints:
#        - key: dremio
#          effect: NoExecute
      requirements:
        - key: "node.kubernetes.io/instance-type"
          operator: In
          values: [ "r6gd.4xlarge", "m6gd.8xlarge" ]
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: [ "eu-central-1a", "eu-central-1b", "eu-central-1c"]
        - key: "kubernetes.io/arch"
          operator: In
          values: [ "arm64" ]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: [ "on-demand" ]
  disruption:
    budgets:
      - nodes: 10%
    consolidateAfter: 30s
    consolidationPolicy: WhenEmptyOrUnderutilized