# https://docs.dremio.com/current/deploy-dremio/configuring-kubernetes/#recommended-resources-configuration
imagePullSecrets: []

dremio:
  trialImagePullCredentials: "PLEASE_SET"
  license: "PLEASE_SET"
  image:
    repository: quay.io/dremio/dremio-enterprise

busyBox:
  image:
    repository: quay.io/dremio/busybox

k8s:
  image:
    repository: quay.io/dremio/alpine/k8s

coordinator:
  volumeSize: 512Gi
  web:
    auth:
      enabled: true
      type: "internal"
    port: 9047
    tls:
      enabled: false
      secret: dremio-tls-secret-ui
  client:
    port: 31010
    tls:
      enabled: false
      secret: dremio-tls-secret-client
  flight:
    port: 32010
    tls:
      enabled: false
      secret: dremio-tls-secret-flight


engine:
  operator:
    image:
      repository: dremiops.azurecr.io/dremio-ee-engine-operator

zookeeper:
  image:
    repository: quay.io/dremio/zookeeper

distStorage:
  aws:
    bucketName: "PLEASE_SET"
    path: "/"
    authentication: "accessKeySecret"
    credentials:
      awsProfileName: default
      accessKey: "PLEASE_SET"
      secret: "PLEASE_SET"

service:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-listener-attributes.TCP-31010: tcp.idle_timeout.seconds=3600
    service.beta.kubernetes.io/aws-load-balancer-listener-attributes.TCP-32010: tcp.idle_timeout.seconds=3600

catalog:
  image:
    repository: quay.io/dremio/dremio-catalog-server
  replicas: 1
  storage:
    location: "PLEASE_SET"
    type: S3
    s3:
      region: "PLEASE_SET"
      useAccessKeys: true
      secretName: catalog-server-s3-storage-creds
      roleArn: "PLEASE_SET"
      userArn: "PLEASE_SET"
  externalAccess:
    enabled: true
    image:
      repository: quay.io/dremio/dremio-catalog-server-external
    replicas: 1

catalogservices:
  image:
    repository: quay.io/dremio/dremio-catalog-services-server

mongodb:
  image:
    repository: quay.io/dremio/percona/percona-server-mongodb
  metrics:
    image:
      repository: quay.io/dremio/percona/mongodb_exporter

mongodbOperator:
  image:
    repository: quay.io/dremio/dremio-mongodb-operator

opensearchOperator:
  manager:
    image:
      repository: quay.io/dremio/dremio-opensearch-operator
  kubeRbacProxy:
    image:
      repository: "quay.io/dremio/kubebuilder/kube-rbac-proxy"

opensearch:
  enabled: true
  image:
    repository: quay.io/dremio/dremio-search-opensearch
  initialAdminPassword: "PLEASE_SET"
  preInstallJob:
    image:
      repository: quay.io/dremio/dremio-search-init

nats:
  enabled: true
  container:
    image:
      repository: quay.io/dremio/nats
  reloader:
    enabled: true
    image:
      repository: quay.io/dremio/natsio/nats-server-config-reloader
  natsBox:
    enabled: true
    container:
      image:
        repository: quay.io/dremio/natsio/nats-box

telemetry:
  enabled: true
  image:
    repository: quay.io/dremio/otel/opentelemetry-collector-contrib

