# https://docs.dremio.com/current/deploy-dremio/configuring-kubernetes/#recommended-resources-configuration
imagePullSecrets: []
writeLogsToFile: true

dremio:
  trialImagePullCredentials: "NOT_SET"
  license: "NOT_SET"
  image:
    repository: quay.io/dremio/dremio-enterprise
    tag: 26.0.0
    pullPolicy: IfNotPresent
  dremioConfExtraOptions: {}
  advancedConfigs: {}
  hive2ConfigFiles: {}
  hive3ConfigFiles: {}
  configFiles: {}
  configBinaries: {}
  log:
    enabled: true
    volume:
      size: 8Gi

busyBox:
  image:
    repository: quay.io/dremio/busybox
    tag: 1.37.0-glibc
    pullPolicy: IfNotPresent

k8s:
  image:
    repository: quay.io/dremio/alpine/k8s
    tag: "1.32.2"
    pullPolicy: IfNotPresent

annotations: {}
podAnnotations: {}
labels: {}
podLabels: {}
nodeSelector: {}

tolerations:
  - key: "dremio"
    operator: "Exists"
    effect: "NoExecute"

coordinator:
  resources:
    requests:
      cpu: "30"
      memory: "112Gi"
    limits:
      memory: "112Gi"
  log:
    volume:
      size: 32Gi
  count: 0
  volumeSize: 512Gi
  storageClass: dremio-coordinator
  logStorageClass: dremio-logs
  serviceAccount: dremio-coordinator
  serviceAccountAnnotations: {}
  autoUpgrade: true
  nodeSelector:
    karpenter.sh/nodepool: dremio-coordinator
  kvstore:
    type: "RocksDB"
  web:
    auth:
      enabled: true
      type: "internal"
    port: 9047
    tls:
      enabled: false
      secret: dremio-tls-secret-ui
  client:
    port: 31010
    tls:
      enabled: false
      secret: dremio-tls-secret-client
  flight:
    port: 32010
    tls:
      enabled: false
      secret: dremio-tls-secret-flight
  startupProbe:
    failureThreshold: 30
    periodSeconds: 10
  livenessProbe:
    failureThreshold: 30
    periodSeconds: 10
  readinessProbe:
    failureThreshold: 12
    periodSeconds: 10
  masterless:
    enabled: false
    replicas: 2

# Conduit Service
conduit:
  port: 45679

engine:
  options:
    sizes:
      - name: XSmall
        pods: 1
        memory: 128Gi
      - name: Small
        pods: 2
        memory: 128Gi
      - name: Medium
        pods: 4
        memory: 128Gi
      - name: Large
        pods: 8
        memory: 128Gi
      - name: XLarge
        pods: 12
        memory: 128Gi
      - name: 2XLarge
        pods: 16
        memory: 128Gi
      - name: 3XLarge
        pods: 24
        memory: 128Gi
      - name: 4XLarge
        pods: 32
        memory: 128Gi
    targetCpuCapacities:
      capacities:
        - name: 16C
          cpu: 16
        - name: 32C
          cpu: 32
      defaultCapacity: 16C
    resourceAllocationOffsets:
      offsets:
        - name: reserve-1-12
          cpu: 1
          memory: 12Gi
          action: Reserve
      defaultOffset: reserve-1-12
    storage:
      spillStorageSizes:
        - name: 300GB
          storage: 300Gi
        - name: 600GB
          storage: 600Gi
      defaultSpillStorageSize: 300GB
      c3StorageSizes:
        - name: 300GB
          storage: 300Gi
        - name: 600GB
          storage: 600Gi
      defaultC3StorageSize: 300GB
    idleTimeouts:
      durations:
        - PT2H
        - PT1H30M
        - PT1H
        - PT30M
        - PT15M
        - PT10M
        - PT5M
      defaultDuration: PT15M
      maximumDuration: PT12H
  operator:
    nodeSelector:
      karpenter.sh/nodepool: dremio-general
    image:
      repository: quay.io/dremio/dremio-engine-operator
      tag: 26.0.0
      pullPolicy: IfNotPresent
    serviceAccount: dremio-engine-operator
    serviceAccountAnnotations: {}
  executor:
    serviceAccount: dremio-engine-executor
    serviceAccountAnnotations: {}
    volumes:
      log:
        pvc:
          storageClass: dremio-logs
          size: 8Gi
      default:
        type: "emptyDir"
        emptyDir:
          sizeLimit: "300Gi"
      c3:
        type: "emptyDir"
        emptyDir:
          sizeLimit: "300Gi"

zookeeper:
  image:
    repository: quay.io/dremio/zookeeper
    tag: 3.8.4-jre-17
    pullPolicy: IfNotPresent
  nodeSelector:
    karpenter.sh/nodepool: dremio-general
  resources:
    requests:
      cpu: "1"
      memory: "2Gi"
    limits:
      memory: "2Gi"
  count: 3
  volumeSize: 10Gi
  storageClass: dremio-zk
  serviceAccount: zookeeper
  serviceAccountAnnotations: {}


distStorage:
  type: "aws"
  aws:
    bucketName: "NOT_SET"
    path: "/"
    authentication: "accessKeySecret"
    credentials:
      awsProfileName: default
      accessKey: "NOT_SET"
      secret: "NOT_SET"
initResources:
  requests:
    cpu: 10m
    memory: 10Mi
  limits:
    cpu: 2000m
    memory: 512Mi

extraVolumes: []

extraVolumeMounts: []

extraEnvs: []

service:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-listener-attributes.TCP-31010: tcp.idle_timeout.seconds=3600
    service.beta.kubernetes.io/aws-load-balancer-listener-attributes.TCP-32010: tcp.idle_timeout.seconds=3600

ddc:
  allowCollectOnAllPods: true
  namespaceDiagnostics: true
  k8sClusterDiagnostic: false

catalog:
  image:
    repository: quay.io/dremio/dremio-catalog-server
    tag: 26.0.0
    pullPolicy: IfNotPresent
  replicas: 1
  serviceAccount: dremio-catalog-server
  serviceAccountAnnotations: {}
  nodeSelector:
    karpenter.sh/nodepool: dremio-general
  extraEnv: []
  extraVolumeMounts: []
  extraVolumes: []
  resources:
    requests:
      cpu: "4"
      memory: "8Gi"
    limits:
      cpu: "4"
      memory: "8Gi"
  storage:
    location: NOT_SET
    type: S3
    s3:
      region: eu-central-1
      useAccessKeys: true
      secretName: catalog-server-s3-storage-creds
      roleArn: "NOT_SET"
      userArn: "NOT_SET"
  externalAccess:
    enabled: true
    image:
      repository: quay.io/dremio/dremio-catalog-server-external
      tag: 26.0.0
      pullPolicy: IfNotPresent
    replicas: 1
    authentication:
      authServerHostname: dremio-master-0.dremio-cluster-pod.{{ .Release.Namespace }}.svc.cluster.local
      disableHostnameVerification: false
    tls:
      enabled: false
      secret: dremio-tls-secret-catalog
    nodeSelector:
      karpenter.sh/nodepool: dremio-general

catalogservices:
  enabled: true
  nodeSelector:
    karpenter.sh/nodepool: dremio-general
  image:
    repository: quay.io/dremio/dremio-catalog-services-server
    tag: 26.0.0
    pullPolicy: IfNotPresent
  serviceAccount: dremio-catalog-services
  serviceAccountAnnotations: {}
  replicas: 1
  resources:
    requests:
      cpu: "4"
      memory: "8Gi"
    limits:
      cpu: "4"
      memory: "8Gi"

mongodb:
  image:
    repository: quay.io/dremio/percona/percona-server-mongodb
    tag: 8.0.4-1-multi
    pullPolicy: IfNotPresent
  metrics:
    image:
      repository: quay.io/dremio/percona/mongodb_exporter
      tag: 0.44.0
      pullPolicy: IfNotPresent
  serviceAccount: dremio-mongodb
  serviceAccountAnnotations: {}
  replicaCount: 3
  labels: { }
  annotations: { }
  nodeSelector:
    karpenter.sh/nodepool: dremio-general
  affinity: { }
  topologySpreadConstraints: [ ]
  storageClass: dremio-mongodb

  tolerations:
    - key: "dremio"
      operator: "Exists"
      effect: "NoExecute"
  resources:
    requests:
      cpu: 2
      memory: 2Gi
    limits:
      cpu: 4
      memory: 2Gi
  enableVolumeExpansion: false
  storage:
    annotations: {}
    labels: {}
    resources:
      requests:
        storage: 256Gi
    accessModes:
    - ReadWriteOnce

mongodbOperator:
  image:
    repository: quay.io/dremio/dremio-mongodb-operator
    tag: 1.19.1-dremio-20250319164744-5670cbfe
  fullnameOverride: "dremio-mongodb-operator"
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  nodeSelector:
    karpenter.sh/nodepool: dremio-general
  tolerations:
    - key: "dremio"
      operator: "Exists"
      effect: "NoExecute"

opensearchOperator:
  useRoleBindings: true
  nodeSelector:
    karpenter.sh/nodepool: dremio-general
  manager:
    image:
      repository: quay.io/dremio/dremio-opensearch-operator
      tag: "2.7.0-dremio-20250404143134-f33f265"
  serviceAccount:
    create: false
    name: dremio-opensearch-operator
    annotations: {}
  kubeRbacProxy:
    image:
      repository: "quay.io/dremio/kubebuilder/kube-rbac-proxy"
      tag: "v0.15.0"

opensearch:
  enabled: true
  clusterName: "opensearch-cluster"
  serviceName: "opensearch-cluster"
  serviceAccount: opensearch-cluster
  serviceAccountAnnotations: { }
  nodeSelector:
    karpenter.sh/nodepool: dremio-general
  image:
    repository: quay.io/dremio/dremio-search-opensearch
    tag: 26.0.0
  version: "2.19.2"
  replicas: 3
  affinity: {}
  volumeSize: "128Gi"
  storageClass: dremio-opensearch
  opensearchJavaOpts: "-XX:InitialRAMPercentage=70.0 -XX:MaxRAMPercentage=70.0"
  # This can be disabled to prevent privileged container, in that
  # case vm.max_map_count must be set on the host: https://opensearch.org/docs/1.0/opensearch/install/important-settings
  setVMMaxMapCount: true
  resources:
    requests:
      memory: "16Gi"
      cpu: "2"
    limits:
      memory: "16Gi"
      cpu: "2"

  tlsCertsSecretName: opensearch-tls-certs
  disableTlsCertGeneration: false
  initialAdminPassword: "NOT_SET"

  oidcProxy:
    nodeSelector:
      karpenter.sh/nodepool: dremio-general
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "256Mi"

  preInstallJob:
    image:
      repository: quay.io/dremio/dremio-search-init
      tag: 26.0.0
    nodeSelector:
      karpenter.sh/nodepool: dremio-general
    serviceAccountAnnotations: {}
  enableHttpBasicAuth: true

nats:
  enabled: true
  # The topologySpreadConstraints ensures NATS pods are distributed evenly across nodes
  # maxSkew: 1 means the difference between nodes with most and least pods can't exceed 1
  # whenUnsatisfiable: DoNotSchedule prevents pod scheduling if constraint can't be met
  podTemplate:
    topologySpreadConstraints:
      kubernetes.io/hostname:
        maxSkew: 1
        whenUnsatisfiable: DoNotSchedule
    merge:
      spec:
        nodeSelector:
          karpenter.sh/nodepool: dremio-general
        tolerations:
          - key: "dremio"
            operator: "Exists"
            effect: "NoExecute"
  config:
    jetstream:
      enabled: true
      fileStore:
        pvc:
          size: 10Gi
          storageClassName: dremio-nats
    cluster:
      enabled: true
      replicas: 3
  container:
    image:
      repository: quay.io/dremio/nats
      tag: 2.11.1-alpine
      pullPolicy: IfNotPresent
    merge:
      resources:
        requests:
          cpu: "500m"
          memory: "1024Mi"
          ephemeral-storage: "50Mi"
        limits:
          cpu: "750m"
          memory: "1536Mi"
          ephemeral-storage: "8Gi"
  reloader:
    enabled: true
    image:
      repository: quay.io/dremio/natsio/nats-server-config-reloader
      tag: 0.17.1
  natsBox:
    enabled: true
    container:
      image:
        repository: quay.io/dremio/natsio/nats-box
        tag: 0.17.0
      merge:
        resources:
          requests:
            cpu: "500m"
            memory: "1024Mi"
          limits:
            cpu: "750m"
            memory: "1536Mi"

telemetry:
  enabled: true
  endpoint: observability.dremio.com:443
  bodySizeLimit: 10MiB
  sendBatchMaxSize: 8192
  metrics:
    scrapeInterval:
      cluster: 5m
      app: 1m

  image:
    repository: quay.io/dremio/otel/opentelemetry-collector-contrib
    tag: 0.117.0
    pullPolicy: IfNotPresent
  goMemLimit: "1638MiB"
  resources:
    requests:
      cpu: "1"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "2Gi"
  extraEnvs: []
  nodeSelector:
    karpenter.sh/nodepool: dremio-general
  clusterId:
    serviceAccountAnnotations: {}

mongodbHooks:
  serviceAccountAnnotations: {}
  podSecurityContext:
    fsGroup: 65534
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    privileged: false
    runAsGroup: 65534
    runAsUser: 65534
