apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: aws-cli
spec:
  serviceName: "aws-cli"
  replicas: 1
  selector:
    matchLabels:
      app: aws-cli
  template:
    metadata:
      labels:
        app: aws-cli
    spec:
      serviceAccountName: default
      automountServiceAccountToken: true
      tolerations:
        - key: dremio
          operator: Exists
          effect: NoExecute
      terminationGracePeriodSeconds: 0
      nodeSelector:
        karpenter.sh/nodepool: dremio-common
      containers:
      - name: aws-cli
        image: amazon/aws-cli
        command: ["sleep", "infinity"]

